// Generated by CoffeeScript 1.6.3
(function() {
  var NODE_ENV, application, config, env, envConfig, util;

  util = require('util');

  application = {
    server: 'tcp://convert.teambition:4033',
    emails: ['jingxin@teambition.com', 'qiang@teambition.com'],
    minUptime: 5000
  };

  env = {
    production: {},
    development: {
      server: 'tcp://localhost:4033'
    },
    mocha: {
      emails: ['jingxin@teambition.com'],
      minUptime: 1000,
      server: 'tcp://localhost:4033'
    }
  };

  NODE_ENV = process.env.NODE_ENV || 'development';

  envConfig = env[NODE_ENV] || env['development'];

  config = util._extend(application, envConfig);

  module.exports = config;

}).call(this);
