// Generated by CoffeeScript 1.6.3
(function() {
  var Handler, async, client, config, handler, logger, os,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  async = require('async');

  client = require('./client.js');

  config = require('./config');

  os = require('os');

  logger = require('graceful-logger');

  Handler = (function() {
    function Handler() {
      this.exception = __bind(this.exception, this);
    }

    Handler.prototype.exception = function(err, clu, callback) {
      var params, pm_uptime, _err, _process, _ref, _ref1, _ref2, _ref3;
      if (callback == null) {
        callback = function() {};
      }
      _err = err.err;
      _process = err.process;
      pm_uptime = ((_ref = _process.pm2_env) != null ? _ref.pm_uptime : void 0) || 0;
      if (!(new Date - pm_uptime > config.minUptime)) {
        return callback(new Error('CRASHTOOFAST'));
      }
      params = {
        date: new Date,
        stack: _err.stack,
        message: _err.message,
        pid: _process.process.pid,
        name: (_ref1 = _process.pm2_env) != null ? _ref1.name : void 0,
        pmId: (_ref2 = _process.pm2_env) != null ? _ref2.pm_id : void 0,
        proc: JSON.stringify(_process, null, 2),
        loadavg: os.loadavg().join(', '),
        freemem: Math.round(os.freemem() / 1024 / 1024) + ' MB',
        uptime: Math.floor((new Date - pm_uptime) / 1000) + ' S'
      };
      logger.warn("exception[" + ((_ref3 = _process.pm2_env) != null ? _ref3.name : void 0) + "]: " + _err.message + " ");
      logger.warn(params);
      return async.each(config.emails, function(to, next) {
        var email;
        email = {
          to: to,
          subject: 'Crash Mail',
          params: params,
          template: 'crashmail'
        };
        return client.call('email.send', email, next);
      }, callback);
    };

    return Handler;

  })();

  handler = new Handler;

  handler.Handler = Handler;

  module.exports = handler;

}).call(this);
