// Generated by CoffeeScript 1.6.3
(function() {
  var logger, monitor;

  logger = require('graceful-logger').format('medium');

  monitor = function() {
    var handler, ipm2;
    ipm2 = require('pm2-interface')();
    handler = require('./handler.js');
    logger.info('thor monitor is online');
    ipm2.on('ready', function() {
      return logger.info('connect to pm2');
    });
    return ipm2.bus.on('process:exception', handler.exception);
  };

  module.exports = monitor;

}).call(this);
